### ISSUE TITLE
Responsive layout css

### ISSUE THREAD

**Issue by jkosem** [jkosem/thepizzacycle#8]

**Comment by jkosem** [comment]
@cfq Last frigging issue and then I do something with it. What I don't know. But in layout.css can't for the life of me get the responsive bit to do the normal thing and get rid of the margins. Then I'm done. Maybe. Probably. Hopefully.

**Comment by jkosem** [comment]
@cfq But it's not really responsive is it? It shrinks but the padding doesn't shrink on smaller width.

Am I going to have to tell you about how every one of my people's child's story is about your people burning villages and killing people? And then a brave peasant boy gets super powers and throws boulders at them?

**Comment by jkosem** [comment]
Okay @cfq I think I give up. Or you tell me it's fine. Then I guess it is.

**Comment by cfq** [comment]
It needs restructuring. I'll have another go later 👍

**Comment by jkosem** [comment]
What needs restructuring? What bit?

The bit I couldn't get going (again, I've done it before) is that on mobile there is a tiny margin, and then on desktop it's a ~800-900px col or something that looks like that with the % padding and that.
